@url = http://localhost:3006

// Cadastrando uma matriz:
POST {{url}}/stores/signup HTTP/1.1
Content-Type: application/json

{
"storeName": "São Paulo Matriz",
"email": "saopaulo@matriz.com",
"password" : "123456789",
"CNPJ": 12345678910,
"adress": "endereço"
}


//Logando uma matriz:
###
POST {{url}}/stores/login HTTP/1.1
Content-Type: application/json

{
    "email": "riopreto@matriz.com",
    "password": "123456789"
}


// Matriz cadastrando uma filial:
###
POST {{url}}/stores/create HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdG9yZUlkIjoiNGU0MWU3ZGEtZjE1Yi00OTEwLTkwNDgtODk4ZDg3NzBhNGZlIiwiaGVhZElkIjoiNGU0MWU3ZGEtZjE1Yi00OTEwLTkwNDgtODk4ZDg3NzBhNGZlIiwicm9sZSI6ImhlYWQiLCJpYXQiOjE2NDY3NzYxNjUsImV4cCI6MTY0Njc5MDU2NX0.XEP-6ckZ_0lgwsoLsuPJEU2WJRzBQ-uQgZDeysMhcOo
{
"storeName": "Paulista",
"email": "paulista@filial.com",
"password" : "123456789",
"CNPJ": 12345678910,
"adress": "endereço"
}


//Logando uma filial:
###
POST {{url}}/stores/login HTTP/1.1
Content-Type: application/json

{
    "email": "vilaitalia@filial.com",
    "password": "123456789"
}


// Alterando uma matriz:
###
PUT {{url}}/stores/cd739290-8dce-41f9-a78c-5dd58ccb64e3 HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdG9yZUlkIjoiNGU0MWU3ZGEtZjE1Yi00OTEwLTkwNDgtODk4ZDg3NzBhNGZlIiwiaGVhZElkIjoiNGU0MWU3ZGEtZjE1Yi00OTEwLTkwNDgtODk4ZDg3NzBhNGZlIiwicm9sZSI6ImhlYWQiLCJpYXQiOjE2NDY3NzYxNjUsImV4cCI6MTY0Njc5MDU2NX0.XEP-6ckZ_0lgwsoLsuPJEU2WJRzBQ-uQgZDeysMhcOo

{
    "adress": "Novo endereço, atualizado pela matriz"
}